import { spawn } from 'child_process'
import { createWriteStream } from 'fs'
import { mkdir, symlink, writeFile } from 'fs/promises'
import net from 'net'
import path from 'path'
import { NextRequest, NextResponse } from 'next/server'
import { requireSession } from '@/lib/session'

const MAX_FILES = 120
const MAX_FILE_CHARS = 300_000
const PREVIEW_PORT_START = 4300
const PREVIEW_PORT_END = 4310
const BLOCKED_SEGMENTS = new Set(['node_modules', '.next', '.git', '.vercel'])
const BLOCKED_FILENAMES = new Set(['.env', '.env.local', '.env.production', '.env.development'])

type LocalPreviewBody = {
  projectName?: string
  files?: Record<string, string>
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || 'nexus-preview'
}

function resolveWorkspaceRoots(): { repoRoot: string; appRoot: string } {
  const cwd = process.cwd()
  const isWebApp = cwd.endsWith(`${path.sep}apps${path.sep}web`)
  const repoRoot = isWebApp ? path.resolve(cwd, '..', '..') : cwd
  const appRoot = isWebApp ? cwd : path.resolve(cwd, 'apps', 'web')
  return { repoRoot, appRoot }
}

function safeRelativeFilePath(filePath: string): string | null {
  const normalizedInput = filePath.replace(/\\/g, '/').replace(/^\/+/, '')
  const segments = normalizedInput.split('/').filter(Boolean)
  if (segments.length === 0) return null
  if (segments.some(segment => segment === '..' || BLOCKED_SEGMENTS.has(segment))) return null
  if (BLOCKED_FILENAMES.has(segments[segments.length - 1])) return null

  const normalized = path.normalize(segments.join(path.sep))
  if (path.isAbsolute(normalized) || normalized.startsWith('..')) return null
  return normalized
}

function baseFiles(projectName: string): Record<string, string> {
  const title = projectName.replace(/[-_]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase()) || 'NEXUS Preview'
  return {
    'package.json': `${JSON.stringify({
      private: true,
      name: slugify(projectName),
      version: '0.1.0',
      scripts: {
        dev: 'next dev --hostname 127.0.0.1',
        build: 'next build',
        start: 'next start --hostname 127.0.0.1',
      },
      dependencies: {
        '@vercel/analytics': 'latest',
        clsx: '^2.1.1',
        'lucide-react': '^0.468.0',
        next: '^15.5.18',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        'tailwind-merge': '^2.5.5',
      },
      devDependencies: {
        '@types/node': '^20',
        '@types/react': '^19',
        '@types/react-dom': '^19',
        autoprefixer: '^10.4.20',
        postcss: '^8.4.49',
        tailwindcss: '^3.4.17',
        typescript: '^5',
      },
    }, null, 2)}\n`,
    'next-env.d.ts': `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated for local NEXUS previews.
`,
    'tsconfig.json': `${JSON.stringify({
      compilerOptions: {
        target: 'ES2017',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    }, null, 2)}\n`,
    'postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,
    'tailwind.config.ts': `import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}

export default config
`,
    'src/app/layout.tsx': `import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: '${title}',
  description: 'Generated by NEXUS OS One-Click Pipeline',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

* { box-sizing: border-box; }
body { margin: 0; background: #f8fafc; color: #0f172a; }
a { color: inherit; text-decoration: none; }
`,
  }
}

async function isPortAvailable(port: number): Promise<boolean> {
  return new Promise(resolve => {
    const server = net.createServer()
    server.once('error', () => resolve(false))
    server.once('listening', () => {
      server.close(() => resolve(true))
    })
    server.listen(port, '127.0.0.1')
  })
}

async function waitForPreview(url: string, timeoutMs = 90_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs
  const urls = [url, `${url}/dashboard`]
  while (Date.now() < deadline) {
    for (const candidate of urls) {
      try {
        const res = await fetch(candidate, { cache: 'no-store' })
        if (res.ok) return true
      } catch {
        // Server is still compiling or not listening yet.
      }
    }
    await new Promise(resolve => setTimeout(resolve, 2000))
  }
  return false
}

async function startPreviewServer(previewDir: string, appRoot: string, port: number): Promise<{ url: string; logPath: string; ready: boolean; command: string }> {
  const url = `http://127.0.0.1:${port}`
  const nextBin = path.join(appRoot, 'node_modules', 'next', 'dist', 'bin', 'next')
  const logPath = path.join(previewDir, 'nexus-local-preview.log')

  // Ensure the log file exists before spawning so createWriteStream has a valid fd on Windows.
  // On Windows, passing a WriteStream whose fd is null to stdio throws ERR_INVALID_ARG_VALUE.
  // We open the stream and wait for the 'open' event before spawning the child process.
  const out = createWriteStream(logPath, { flags: 'a' })
  await new Promise<void>((resolve, reject) => {
    out.once('open', () => resolve())
    out.once('error', reject)
  })

  const child = spawn(process.execPath, [nextBin, 'dev', '-p', String(port), '-H', '127.0.0.1'], {
    cwd: previewDir,
    detached: true,
    env: {
      ...process.env,
      NEXT_TELEMETRY_DISABLED: '1',
      PORT: String(port),
    },
    stdio: ['ignore', out, out],
    windowsHide: true,
  })
  child.unref()

  return {
    url,
    logPath,
    ready: await waitForPreview(url),
    command: `node "${nextBin}" dev -p ${port} -H 127.0.0.1`,
  }
}

async function startPreviewServerWithPortRetry(previewDir: string, appRoot: string): Promise<{ url: string; logPath: string; ready: boolean; command: string; port: number }> {
  let lastError: unknown
  for (let port = PREVIEW_PORT_START; port <= PREVIEW_PORT_END; port++) {
    if (!(await isPortAvailable(port))) continue
    try {
      const preview = await startPreviewServer(previewDir, appRoot, port)
      return { ...preview, port }
    } catch (err) {
      lastError = err
    }
  }
  throw lastError instanceof Error ? lastError : new Error('No local preview port is available')
}

export async function POST(req: NextRequest) {
  // Local preview requires a writable filesystem — unavailable on Vercel serverless.
  // Return a clear skip signal so the pipeline continues without failing.
  if (process.env.VERCEL || process.env.VERCEL_ENV || process.env.AWS_LAMBDA_FUNCTION_NAME) {
    return NextResponse.json({
      ok: false,
      error: 'Local preview is not available in serverless deployments. Files have been generated and will be pushed to GitHub.',
      isServerless: true,
    }, { status: 200 })
  }

  const session = await requireSession()
  if (session.error) return session.error

  let body: LocalPreviewBody
  try {
    body = await req.json() as LocalPreviewBody
  } catch {
    return NextResponse.json({ ok: false, error: 'Invalid JSON body' }, { status: 400 })
  }

  const incomingFiles = body.files ?? {}
  const entries = Object.entries(incomingFiles).filter(([, content]) => typeof content === 'string')
  if (entries.length === 0) {
    return NextResponse.json({ ok: false, error: 'No generated files available for local preview' }, { status: 400 })
  }
  if (entries.length > MAX_FILES) {
    return NextResponse.json({ ok: false, error: `Too many files for local preview (${entries.length}/${MAX_FILES})` }, { status: 400 })
  }

  const projectName = slugify(body.projectName || 'nexus-preview')
  const runId = `${new Date().toISOString().replace(/[^0-9]/g, '').slice(0, 14)}-${Math.random().toString(36).slice(2, 7)}`
  const { repoRoot, appRoot } = resolveWorkspaceRoots()
  const previewRoot = path.join(repoRoot, '.nexus-previews')
  const previewDir = path.join(previewRoot, `${projectName}-${runId}`)

  await mkdir(previewDir, { recursive: true })

  const filesToWrite = { ...baseFiles(projectName), ...incomingFiles }
  const written: string[] = []
  const skipped: string[] = []

  for (const [filePath, rawContent] of Object.entries(filesToWrite)) {
    const safePath = safeRelativeFilePath(filePath)
    const content = typeof rawContent === 'string' ? rawContent.slice(0, MAX_FILE_CHARS) : ''
    if (!safePath || !content.trim()) {
      skipped.push(filePath)
      continue
    }
    const target = path.join(previewDir, safePath)
    if (!target.startsWith(previewDir)) {
      skipped.push(filePath)
      continue
    }
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, content, 'utf8')
    written.push(filePath)
  }

  let nodeModulesLinked = false
  try {
    await symlink(path.join(appRoot, 'node_modules'), path.join(previewDir, 'node_modules'), 'junction')
    nodeModulesLinked = true
  } catch {
    nodeModulesLinked = false
  }

  let preview: Awaited<ReturnType<typeof startPreviewServerWithPortRetry>>
  try {
    preview = await startPreviewServerWithPortRetry(previewDir, appRoot)
  } catch (err) {
    const message = (err as Error).message || 'Local preview server could not be started'
    return NextResponse.json({
      ok: false,
      error: message,
      data: {
        path: previewDir,
        projectName,
        fileCount: written.length,
        skipped,
        nodeModulesLinked,
      },
    }, { status: 200 })
  }

  return NextResponse.json({
    ok: preview.ready,
    ...(preview.ready ? {} : { error: `Local preview files were written, but the dev server did not respond at ${preview.url}. Check ${preview.logPath}` }),
    data: {
      path: previewDir,
      projectName,
      fileCount: written.length,
      skipped,
      nodeModulesLinked,
      url: preview.url,
      port: preview.port,
      ready: preview.ready,
      command: preview.command,
      logPath: preview.logPath,
    },
  }, { status: 200 })
}
