import { NextRequest, NextResponse } from 'next/server'
import { requireSession } from '@/lib/session'
import { checkRateLimit } from '@/lib/ratelimit'

async function gh(path: string, token: string, method = 'GET', body?: object) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept:        'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    const errBody = await res.json().catch(() => ({ message: res.statusText }))
    const detail = Array.isArray(errBody.errors) && errBody.errors.length > 0
      ? errBody.errors[0].message
      : errBody.message
    throw new Error(`GitHub ${method} ${path}: ${detail ?? res.statusText}`)
  }
  return res.json()
}

// Retry wrapper — exponential backoff on transient 5xx / rate-limit errors
async function ghRetry(path: string, token: string, method = 'GET', body?: object, retries = 3) {
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      return await gh(path, token, method, body)
    } catch (err) {
      const msg = (err as Error).message ?? ''
      const isTransient = /5\d\d|rate.?limit|timeout|ECONNRESET|ETIMEDOUT/i.test(msg)
      if (!isTransient || attempt === retries - 1) throw err
      await new Promise(r => setTimeout(r, Math.pow(2, attempt) * 600))
    }
  }
  throw new Error('GitHub: exhausted retries')
}

async function repoExists(owner: string, name: string, token: string): Promise<boolean> {
  const res = await fetch(`https://api.github.com/repos/${owner}/${name}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' },
  })
  return res.status === 200
}

export async function POST(req: NextRequest) {
  const auth = await requireSession()
  if (auth.error) return auth.error

  // Rate-limit deploy calls — 10/min per user (pipeline makes 2 calls per run: spec + app repo)
  const rl = await checkRateLimit(`deploy:gh:${auth.user.id}`)
  if (!rl.success) {
    return NextResponse.json(
      { ok: false, error: 'Deploy rate limit reached. Max 10 GitHub repo creations per minute.' },
      { status: 429, headers: { 'Retry-After': '60', 'X-RateLimit-Remaining': '0' } }
    )
  }

  const { repoName, files, token: bodyToken, isPrivate = true, description } = await req.json() as {
    repoName:    string
    files:       Record<string, string>
    token?:      string
    isPrivate?:  boolean
    description?: string
  }

  // Server env var takes precedence — client token is fallback for advanced users
  const token = process.env.GITHUB_TOKEN?.trim() || bodyToken?.trim() || ''

  if (!token) {
    return NextResponse.json({ ok: false, error: 'No GitHub token configured. Set GITHUB_TOKEN in environment or provide one in the UI.' }, { status: 400 })
  }
  if (!repoName || !files || Object.keys(files).length === 0) {
    return NextResponse.json({ ok: false, error: 'repoName and files are required' }, { status: 400 })
  }

  // Sanitise repo name and description
  const baseName    = repoName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').slice(0, 100)
  const safeDesc    = (description ?? 'Generated by NEXUS OS FORGE')
    .replace(/[\x00-\x1F\x7F]/g, ' ')  // strip control characters incl. newlines
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 350)

  try {
    // 1. Get authenticated user
    const user = await gh('/user', token)
    const owner: string = user.login

    // 2. Create repo — pre-check existence, add suffix proactively if taken
    let finalName = baseName
    if (await repoExists(owner, finalName, token)) {
      finalName = `${baseName}-${Date.now().toString(36).slice(-5)}`
    }
    await gh('/user/repos', token, 'POST', {
      name:        finalName,
      description: safeDesc,
      private:     isPrivate,
      auto_init:   true,
    })

    // 3. Get default branch SHA
    const repoData  = await gh(`/repos/${owner}/${finalName}`, token)
    const branch    = repoData.default_branch ?? 'main'
    const refData   = await gh(`/repos/${owner}/${finalName}/git/refs/heads/${branch}`, token)
    const latestSHA: string = refData.object.sha
    const commitData = await gh(`/repos/${owner}/${finalName}/git/commits/${latestSHA}`, token)
    const baseTreeSHA: string = commitData.tree.sha

    // 4. Create blobs in parallel (10 at a time) — per-blob catch so one failure doesn't kill the batch
    const CONCURRENCY = 10
    const entries = Object.entries(files).filter(([p, c]) => !!p && !!c)
    const treeItems: { path: string; mode: string; type: string; sha: string }[] = []
    const blobErrors: string[] = []
    for (let i = 0; i < entries.length; i += CONCURRENCY) {
      const batch = entries.slice(i, i + CONCURRENCY)
      const settled = await Promise.allSettled(batch.map(async ([filePath, content]) => {
        const blob = await ghRetry(`/repos/${owner}/${finalName}/git/blobs`, token, 'POST', {
          content:  Buffer.from(content as string).toString('base64'),
          encoding: 'base64',
        })
        return { path: filePath, mode: '100644', type: 'blob', sha: blob.sha as string }
      }))
      for (const r of settled) {
        if (r.status === 'fulfilled') treeItems.push(r.value)
        else blobErrors.push((r.reason as Error).message?.slice(0, 120) ?? 'unknown blob error')
      }
    }
    if (blobErrors.length > 0) {
      console.warn(`GitHub blob upload: ${blobErrors.length} file(s) failed —`, blobErrors.slice(0, 5))
    }
    if (treeItems.length === 0) {
      throw new Error(`All ${entries.length} blob uploads failed — check GitHub token permissions`)
    }

    // 5. Create tree
    const tree = await gh(`/repos/${owner}/${finalName}/git/trees`, token, 'POST', {
      base_tree: baseTreeSHA,
      tree:      treeItems,
    })

    // 6. Create commit
    const commit = await gh(`/repos/${owner}/${finalName}/git/commits`, token, 'POST', {
      message: 'Initial commit from NEXUS OS FORGE',
      tree:    tree.sha,
      parents: [latestSHA],
    })

    // 7. Update branch ref
    await gh(`/repos/${owner}/${finalName}/git/refs/heads/${branch}`, token, 'PATCH', {
      sha:   commit.sha,
      force: false,
    })

    const repoUrl     = `https://github.com/${owner}/${finalName}`
    const vercelImport = `https://vercel.com/new/clone?repository-url=${encodeURIComponent(repoUrl)}&project-name=${finalName}`

    return NextResponse.json({
      ok: true,
      data: {
        repoUrl,
        vercelImport,
        owner,
        repo:        finalName,
        branch,
        files:       treeItems.length,
        blobErrors:  blobErrors.length > 0 ? blobErrors.length : undefined,
      },
    })
  } catch (err) {
    return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 500 })
  }
}

// Verify token — uses server env var if no token param provided
export async function GET(req: NextRequest) {
  const auth = await requireSession()
  if (auth.error) return auth.error

  const paramToken  = req.nextUrl.searchParams.get('token') ?? ''
  const token       = process.env.GITHUB_TOKEN?.trim() || paramToken
  const isServerKey = !!process.env.GITHUB_TOKEN?.trim()

  if (!token) return NextResponse.json({ ok: false, error: 'token required' }, { status: 400 })

  try {
    const user = await gh('/user', token)
    return NextResponse.json({ ok: true, data: { login: user.login, avatar: user.avatar_url, isServerKey } })
  } catch (err) {
    return NextResponse.json({ ok: false, error: (err as Error).message }, { status: 401 })
  }
}
