import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service — NEXUS OS',
  description: 'Terms of service for NEXUS OS.',
}

const EFFECTIVE_DATE = '1 May 2025'

export default function TermsPage() {
  return (
    <div style={{ background: '#0a0a0f', color: '#e2e8f0', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, monospace', minHeight: '100vh', padding: '3rem 2rem' }}>
      <div style={{ maxWidth: '680px', margin: '0 auto' }}>
        <Link href="/" style={{ color: '#a78bfa', textDecoration: 'none', fontSize: '0.85rem' }}>← NEXUS OS</Link>
        <h1 style={{ fontSize: '1.75rem', fontWeight: 800, marginTop: '2rem', marginBottom: '0.5rem', color: '#f1f5f9' }}>Terms of Service</h1>
        <p style={{ color: '#475569', fontSize: '0.85rem', marginBottom: '3rem' }}>Effective date: {EFFECTIVE_DATE}</p>

        {[
          {
            title: '1. Acceptance',
            body: 'By accessing or using NEXUS OS ("the Service"), you agree to be bound by these Terms. If you do not agree, do not use the Service.',
          },
          {
            title: '2. Description of Service',
            body: 'NEXUS OS is an AI-powered software development platform that uses multiple AI agents to generate project specifications, architecture documents, code scaffolds, security reports, and go-to-market materials. The Service is provided on a subscription basis.',
          },
          {
            title: '3. Account Registration',
            body: 'You must create an account to use most features. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must provide accurate information and keep it updated.',
          },
          {
            title: '4. Acceptable Use',
            body: 'You agree not to: (a) use the Service for illegal purposes; (b) attempt to reverse engineer the AI models; (c) resell or sublicense the Service without written permission; (d) generate content that violates applicable laws or third-party rights; (e) abuse the shared quota system by running automated pipelines beyond stated plan limits.',
          },
          {
            title: '5. Payment & Subscriptions',
            body: 'Paid plans are billed monthly in advance. All fees are non-refundable except as required by law. We reserve the right to change pricing with 30 days notice. Unpaid accounts may be suspended after a grace period.',
          },
          {
            title: '6. AI-Generated Content',
            body: 'Content generated by the Service is produced by AI and may contain errors. You are responsible for reviewing, validating, and testing all generated code and documents before use in production. We make no warranty that generated content is accurate, complete, secure, or fit for any particular purpose.',
          },
          {
            title: '7. Intellectual Property',
            body: 'You retain ownership of the input you provide and the output generated from your input. We retain ownership of the platform, models, and systems. You grant us a limited license to process your input for the purpose of providing the Service.',
          },
          {
            title: '8. Data & Privacy',
            body: 'Your use of the Service is also governed by our Privacy Policy. We do not sell your personal data. Pipeline inputs and outputs may be used in aggregate, anonymised form to improve the Service unless you opt out in Settings.',
          },
          {
            title: '9. Quota & Fair Use',
            body: 'Each plan includes a monthly run quota. Unused runs do not roll over. We reserve the right to rate-limit or suspend accounts that abuse the quota system or place abnormal load on shared infrastructure.',
          },
          {
            title: '10. Disclaimers',
            body: 'The Service is provided "as is" and "as available" without warranty of any kind. We disclaim all warranties, express or implied, including merchantability, fitness for a particular purpose, and non-infringement.',
          },
          {
            title: '11. Limitation of Liability',
            body: 'To the maximum extent permitted by law, our total liability for any claim arising from or related to the Service shall not exceed the amount you paid us in the 12 months preceding the claim.',
          },
          {
            title: '12. Termination',
            body: 'Either party may terminate at any time. We may suspend or terminate accounts that violate these Terms. Upon termination, your right to use the Service ceases immediately.',
          },
          {
            title: '13. Changes to Terms',
            body: 'We may update these Terms at any time. We will notify you by email or in-app notice at least 14 days before material changes take effect. Continued use after that date constitutes acceptance.',
          },
          {
            title: '14. Contact',
            body: `For questions about these Terms, contact us at support@nexus-os.ai`,
          },
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1rem', fontWeight: 700, color: '#a78bfa', marginBottom: '0.5rem' }}>{title}</h2>
            <p style={{ fontSize: '0.875rem', color: '#94a3b8', lineHeight: 1.7 }}>{body}</p>
          </div>
        ))}

        <div style={{ borderTop: '1px solid #1e1e2e', paddingTop: '2rem', marginTop: '2rem', display: 'flex', gap: '2rem', fontSize: '0.8rem' }}>
          <Link href="/privacy" style={{ color: '#a78bfa', textDecoration: 'none' }}>Privacy Policy</Link>
          <Link href="/" style={{ color: '#475569', textDecoration: 'none' }}>Home</Link>
        </div>
      </div>
    </div>
  )
}
